algorithm: comatch
save_dir: ./saved_models/usb_cv/
save_name: comatch_stl10_100_0
resume: True
load_path: ./saved_models/usb_cv//comatch_stl10_100_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 100
uratio: 1
ema_m: 0.999
hard_label: False
p_cutoff: 0.95
contrast_p_cutoff: 0.8
contrast_loss_ratio: 5.0
ulb_loss_ratio: 1.0
proj_size: 64
queue_batch: 32
smoothing_alpha: 0.9
T: 0.2
da_len: 32
img_size: 96
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
layer_decay: 0.65
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_base_patch16_96
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10070
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/mae_pretrain_vit_base.pth
