algorithm: freematch
save_dir: ./saved_models/usb_nlp
save_name: freematch_dbpedia_280_0
resume: True
load_path: ./saved_models/usb_nlp/freematch_dbpedia_280_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_warmup_iter: 5120
num_log_iter: 256
num_eval_iter: 2048
num_labels: 280
batch_size: 8
eval_batch_size: 8
ema_m: 0.0
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001
uratio: 1
use_cat: False
optim: AdamW
lr: 1e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: bert_base_uncased
net_from_name: False
data_dir: ./data
dataset: dbpedia
train_sampler: RandomSampler
num_classes: 14
num_workers: 4
max_length: 512
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10106
dist_backend: nccl
gpu: None
