algorithm: fixmatch
save_dir: ./saved_models/SemiReward/usb_cv/fixmatch/
save_name: fixmatch_imagenet_100000_0_p095
resume: True
load_path: ./saved_models/SemiReward/usb_cv/fixmatch//fixmatch_imagenet_100000_0_p095/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 20
num_train_iter: 2000000
num_log_iter: 1000
num_eval_iter: 10000
batch_size: 32
eval_batch_size: 256
num_warmup_iter: 0
num_labels: 100000
uratio: 7
ema_m: 0.999
hard_label: True
T: 0.5
thresh_warmup: True
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 224
crop_ratio: 0.875
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: True
clip: 0.0
net: resnet50
net_from_name: False
data_dir: ./data
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10006
dist_backend: nccl
gpu: None
use_pretrain: True
find_unused_parameters: False
