algorithm: meanteacher
save_dir: ./saved_models/classic_cv
save_name: meanteacher_cifar100_10000_0
resume: True
load_path: ./saved_models/classic_cv/meanteacher_cifar100_10000_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 1024
num_train_iter: 1048576
num_eval_iter: 5120
num_log_iter: 256
num_labels: 10000
batch_size: 64
eval_batch_size: 256
uratio: 1
ulb_loss_ratio: 50
unsup_warm_up: 0.4
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10033
dist_backend: nccl
gpu: None
